[package]
name = "ezmi2d-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
ezmi2d-core = { path = "../crates/ezmi2d-core" }
libfuzzer-sys = "0.4"

[[bin]]
name = "raw_scan"
path = "fuzz_targets/raw_scan.rs"
test = false
doc = false
bench = false

[[bin]]
name = "semantic_read"
path = "fuzz_targets/semantic_read.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
