from typing import Any, Final

DEFAULT_MAX_FILE_SIZE_BYTES: Final[int]
DEFAULT_MAX_LINES: Final[int]
DEFAULT_MAX_SECTIONS: Final[int]
DEFAULT_MAX_RECORDS: Final[int]
DEFAULT_MAX_LINE_SIZE_BYTES: Final[int]
DEFAULT_MAX_RECORD_SIZE_BYTES: Final[int]
DEFAULT_MAX_DECOMPRESSED_SIZE_BYTES: Final[int]
DEFAULT_MAX_COMPRESSION_RATIO: Final[int]

class MiError(Exception): ...
class InvalidMiError(MiError): ...
class UnsupportedMiError(MiError): ...
class MiLimitError(MiError): ...

def core_version() -> str: ...
def detect_format_bytes(data: bytes) -> dict[str, Any]: ...
def scan_mi_records(data: bytes, limits: list[int]) -> dict[str, Any]: ...
def read_legacy_document(
    data: bytes, limits: list[int], encoding: str | None = None
) -> dict[str, Any]: ...
